final changes

diff --git a/php/Dockerfile b/php/Dockerfile
--- a/php/Dockerfile
+++ b/php/Dockerfile
@@ -1,6 +1,13 @@
-FROM php:8.2-fpm-alpine
+FROM php:8.2-fpm-alpine as app
 
-RUN docker-php-ext-install pdo pdo_mysql
+# php extension installer, copy binary into container
+COPY --from=mlocati/php-extension-installer /usr/bin/install-php-extensions /usr/local/bin/
+
+# exit on errors set,
+RUN set -eux; \
+    install-php-extensions pdo pdo_mysql
+
+# RUN docker-php-ext-install pdo pdo_mysql
 
 # super user to use composer from terminal as docker
 ENV COMPOSER_ALLOW_SUPERUSER=1
@@ -19,3 +26,12 @@ RUN  composer install --prefer-dist --no-dev --no-scripts --no-progress --no-int
 COPY ./app .
 
 RUN composer dump-autoload --optimize
+
+FROM app as app_dev
+
+ENV XDEBUG_MODE=off
+
+COPY ./php/conf.d/xdebug.ini $PHP_INI_DIR/conf.d/
+
+RUN set -eux; \
+    install-php-extensions xdebug
